import 'package:domino_point/src/helper/assets.dart';

class SPConst {
  /* 
  ["0_0","0_1","0_2","0_3","0_4","0_5","0_6",],
  ["1_0","1_1","1_2","1_3","1_4","1_5","1_6",],
  ["2_0","2_1","2_2","2_3","2_4","2_5","2_6",],
  ["3_0","3_1","3_2","3_3","3_4","3_5","3_6",],
  ["4_0","4_1","4_2","4_3","4_4","4_5","4_6",],
  ["5_0","5_1","5_2","5_3","5_4","5_5","5_6",],
  ["6_0","6_1","6_2","6_3","6_4","6_5","6_6",],   
  */

  static const List<List<String>> domnino = [
    [
      Assets.assetsDomino00,
      Assets.assetsDomino01,
      Assets.assetsDomino02,
      Assets.assetsDomino03,
      Assets.assetsDomino04,
      Assets.assetsDomino05,
      Assets.assetsDomino06,
    ],
    [
      Assets.assetsDomino10,
      Assets.assetsDomino11,
      Assets.assetsDomino12,
      Assets.assetsDomino13,
      Assets.assetsDomino14,
      Assets.assetsDomino15,
      Assets.assetsDomino16,
    ],
    [
      Assets.assetsDomino20,
      Assets.assetsDomino21,
      Assets.assetsDomino22,
      Assets.assetsDomino23,
      Assets.assetsDomino24,
      Assets.assetsDomino25,
      Assets.assetsDomino26,
    ],
    [
      Assets.assetsDomino30,
      Assets.assetsDomino31,
      Assets.assetsDomino32,
      Assets.assetsDomino33,
      Assets.assetsDomino34,
      Assets.assetsDomino35,
      Assets.assetsDomino36,
    ],
    [
      Assets.assetsDomino40,
      Assets.assetsDomino41,
      Assets.assetsDomino42,
      Assets.assetsDomino43,
      Assets.assetsDomino44,
      Assets.assetsDomino45,
      Assets.assetsDomino46,
    ],
    [
      Assets.assetsDomino50,
      Assets.assetsDomino51,
      Assets.assetsDomino52,
      Assets.assetsDomino53,
      Assets.assetsDomino54,
      Assets.assetsDomino55,
      Assets.assetsDomino56,
    ],
    [
      Assets.assetsDomino60,
      Assets.assetsDomino61,
      Assets.assetsDomino62,
      Assets.assetsDomino63,
      Assets.assetsDomino64,
      Assets.assetsDomino65,
      Assets.assetsDomino66,
    ],
  ];
}
